saltstack-formulas/users-formula

pillar.example
users/init.sls

If you name your keys after your users, I think this can make the users pillar very concise. e.g. something like:
```
{%- load_yaml as userlist %}
- user1
- user2
- ...
{%- endload %}
users:
{%- for user in userlist %}
{{ user }}:
ssh_auth_sources:
- salt://keys/{{ user }}.id_rsa.pub
{%- endfor %}
```

Added option to source ssh public keys from files.

---

pillar.example
users/init.sls

If you like to keep your ssh keys in a separate pillar, because, for example you need to deploy them to the root user as well, you can now use this formula without repeating yourself. 
I have added the ability to pull ssh keys from a different pillar that could for example, look like this:
```yaml
ssh_keys:
id_rsa:
privkey: |
-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAoQiwO3JhBquPAalQF9qP1lLZNXVjYMIswrMe2HcWUVBgh+vY
U7sCwx/dH6+VvNwmCoqmNnP+8gTPKGl1vgAObJAnMT623dMXjVKwnEagZPRJIxDy
B/HaAre9euNiY3LvIzBTWRSeMfT+rWvIKVBpvwlgGrfgz70m0pqxu+UyFbAGLin+
GpxzZAMaFpZw4sSbIlRuissXZj/sHpQb8p9M5IeO4Z3rjkCP1cxI
-----END RSA PRIVATE KEY-----
pubkey: |
ssh-rsa MIIEowIBAAKCAQEAoQiwO3JhBquPAalQF9qP1lLZNXVjYMIswrMe2H....
```

Add the ability to pull ssh keys from a different pillar

---

users/bashrc.sls
users/files/bashrc/bashrc

This will ensure a given bashrc file in a users home dir.
Default it will search for a bashrc in salt://users/files/bashrc/{{ username }}/bashrc
If no file is found it will install the default from
salt://users/files/bashrc/bashrc

Added bashrc extension to users-formula

---

pillar.example

Add a simple sudo_rules example for a rule with colons (For more info check issue #74)

Add sudo_rules syntax examples for rules with colons

---

users/init.sls

When using the ssh_auth_file pillar option to create an authorized_hosts file, the .ssh directory was not being created causing a highstate to fail. This will create the user's .ssh directory if the ssh_auth_file option was set.

the user's .ssh directory should be created if ssh_auth_file is supplied

---

pillar.example
users/init.sls

Added ability to specify room number, home phone, and work phone as per https://docs.saltstack.com/en/develop/ref/states/all/salt.states.user.html.  This gives the user the ability to avoid having "fullname,,," in GECOS field in /etc/passwd and allows to fully populate the GECOS field.

Added ability to specify room number, home phone, and work phone

---

users/init.sls

This version complains that "argument port can not be used in
conjunction with argument hash_hostname", so add hash_hostname
to the fields we handle in the formula so we can override it
if needed.

Fix minor bug for ssh known_hosts management with salt >= 2015.5.5.

---

users/init.sls

When running  ```state.highstate test=true```  users-formula reports changes when no changes are required.
```
salt-ssh testhost state.highstate test=true
testhost:
Name: visudo -cf - <<<"$rule" | { read output; if [[ $output != "stdin: parsed OK" ]] ; then echo $output ; fi } - Function: cmd.run - Result: Differs
```
This commit introduces new logic for verifying sudo rules. So I just commented out old logic-block.
More details:
https://github.com/saltstack-formulas/users-formula/issues/95

changing visudo checking to avoid wrong reporting when launched in a test mode

---

users/init.sls
users/sudo.sls

This formula doesn't really require the sudo group (unless
there are actually users in that group). Moreover, on FreeBSD
the 'admin' group would be wheel and not sudo.

Don't add sudo group by default.

---

users/init.sls

(See [Salt issue #29004](https://github.com/saltstack/salt/issues/29004))
Unreasonable values for 'expire' (after 9999-12-31
on Linux, before 1975-01-01 on *BSD) get divided
by 86400 (number of seconds in a day) when too big
or multiplied by 86400 when too small.
Tested on CentOS 6 (Salt 2015.5.5) and FreeBSD 10.2
(Salt 2015.8.0) with following values:
- 24854 (2038-01-18 in days since epoch)
- 157766400 (1975-01-01 00:00:00 UTC in seconds since epoch)
- 3313526400 (2075-01-01 00:00:00 UTC in seconds since epoch)
- 16000 (2013-10-22 in days since epoch)
- 18000 (2019-04-14 in days since epoch)
(Sponsored by av.tu-berlin.de and fokus.fraunhofer.de)

Mitigate Salt issue #29004, fixes "expire" on *BSD

---

users/init.sls

If a primary group is set on the user, and a authorized_keys is provied in ssh_auth_file, the formula fails. This solves that by using the user_group set earlier in the formula

Use the primary group for the user when creating authorized_keys

---

users/init.sls

In order to load ssh public keys from pillar I had to make this change.

also load ssh keys from pillar data

---

users/user_files.sls

Without `home` parameter in pillar file the following error occurs during highstate process:
> Rendering SLS 'base:users.user_files' failed: Jinja variable 'collections.OrderedDict object' has no attribute 'home'

User files state without defined home directory

---

users/user_files.sls

Reverts saltstack-formulas/users-formula#107 to resolve https://github.com/saltstack-formulas/users-formula/issues/111, should probably come up with a better way to do this.

Revert "User files state without defined home directory"

---

users/user_files.sls

Fix for #99 with style/pattern already used in formula.
Currently if 'home' option omitted in pillar you will get error:
`Rendering SLS 'base:users.user_files' failed: Jinja variable 'dict object' has no attribute 'home'`
With this fix you will get `/home/%username%` as default path for user home folder. It doesn't cover all possible situations as @0xf10e pointed there [1](https://github.com/saltstack-formulas/users-formula/pull/100#issuecomment-156035096) [2](https://github.com/saltstack-formulas/users-formula/pull/100#issuecomment-156350893) but it's better than nothing.

Default path for home folder in user_files.sls if home omitted in pillar [fixed style].

---

pillar.example
users/init.sls

Resolution for #115.
Credit given where credit due (IRC #salt): @babilen @Sylvain31 @RealMurphy @iggy (shame if that doesn't link correctly).
This was the answer suggested when I asked how to use Salt to simply check if Git is installed on a minion.  All I had to do was put it together.  I've tested with another git-less minion and AOK.

Resolve `git.config` error where minion does not have Git installed #115

---

users/init.sls

If the user to be created is a system user, it makes no sense to create
him a primary group which is not a system group too.

Create a system usergroup if user is a system user

---

pillar.example
users/init.sls

Found some commits that I had intended to include in a PR from the end of last year!  They still apply cleanly and are probably useful.
Additional reasoning for the `Use contents_pillar to work with multiple-line authorized_keys file` commit:
1. Also consistent use of `contents_pillar` with earlier in the file
1. Replaces deprecated `iteritems`

Use `contents_pillar` to work with multi-line authorized_keys file

---

users/bashrc.sls
users/init.sls
users/profile.sls
users/user_files.sls
users/vimrc.sls

Hi there,
This PR adds the following feature.
If a user account already exists, and home or shell are not explicitly defined in pillar configuration, current values are retained instead of being forced to /home/<user> and /bin/bash.
Use case:
I only wanted to use this formula for the sudoers and user_files function. (system)User is added as part of a package, so it already exists. Homedir and shell may vary depending on the OS/dist, so I'd like to retain it if possible.
Furthermore i noticed that all homedir references in SSH key management states could be made shorter as the choice for {{ home }} is already made

Keep existing user's home and shell unless explicitly defined

---

pillar.example
users/init.sls

Simple change to pass `optional_groups` from the pillar to `user.present`.

Support for optional_groups

---

users/init.sls

Added replace:False to file.managed sudoers.d/file
This will fix the warning:
```
[WARNING ] State for file: /etc/sudoers.d/<username> - Neither 'source' nor 'contents' nor 'contents_pillar' nor 'contents_grains' was defined, yet 'replace' was set to 'True'. As there is no source to replace the file with, 'replace' has been set to 'False' to avoid reading the file unnecessarily.
```

fix warning on managed file state for /etc/sudoers.d/username

---

users/init.sls

Found this bug while using absent_users. It breaks state rendering. This patch fixes it.

fix wrong variable name in absent_users

---

users/init.sls

The checks on whether git is installed (and therefore executable) are failing for me. Therefore this is a temporary fix that probably has a better resolution.

temp fix on git executable

---

users/bashrc.sls

We have some more complex rules for our bashrc files, putting content depending on environments, etc.

Add support for jinja code in bashrc files.

---

users/profile.sls
users/vimrc.sls

We've got some environment variables within bash profiles which should be set from pillar data.

Add ability to use templated user files

---

README.rst
pillar.example
users/map.jinja

Successor of #154 
```yaml
users:
lookup:
```
Actually defined another user. This PR introduces `users-formula` to solve this issue.

(Re-)enable pillar users-formula:lookup

---

users/init.sls

Fixing my previous change which errors in a particular scenario.
Fixes #150 #151 
Error: Conflicting ID 'users_ssh_auth_source_username_0' when keys are added and removed simultaneously.

Fixing a bug introduced in my previous commit

---

pillar.example
users/user_files.sls

This PR add minor improvement by adding ability to specify mode for files and symlinks in user_files.
Unfortunately dir_mode interfere with user_dir_mode therefore I didn't add it.
For me key value is new (since 2016.11.0) 'keep' option for file_mode, now files in $HOME/bin can save their execution bit.

Add ability to specify mode for files and symlinks in user_files

---

users/init.sls

The creation of ssh authorized_keys containing multiple keys is broken if contents_pillar option is used. It only used the first item in list. I "reverted" it to use the content option, which works now.

fixed insertion of multiple authorized keys via ssh_auth_pillar

---

users/user_files.sls

Change to include `template` caused compile issue due to the wrong format for the conditional.
Additionally, results produced from the template would not have had proper line-spacing on the new entry.

Broken conditional and lack of line spacing

---

users/init.sls

The [check of the saltversioninfo](https://github.com/saltstack-formulas/users-formula/blob/e5e9cd8fcfaaa8fe76aa3ce1d98436b156fb9171/users/init.sls#L465) doesn't work for the git config setup. This change fixes the problem. I looked for saltversioninfo checks in [other formulas](https://github.com/saltstack-formulas/maven-formula/blob/77db29e532e032b724bca376860af6d9203edad2/maven/init.sls#L35), to find out how it is done.  
The error  for me was always:
```
----------
ID: users_root_user_gitconfig_0
Function: git.config
Name: push.default
Result: False
Comment: State 'git.config' was not found in SLS 'users'
Reason: 'git.config' is not available.
Changes:
----------
ID: users_root_user_gitconfig_1
Function: git.config
Name: url."https://".insteadOf
Result: False
Comment: State …
```

corrected saltversioninfo check expression

---

users/init.sls

The state will not fail gracefully, instead you will get
an error like this one:
ID: users_rhertzog_user_gitconfig_0
Function: git.config_set
Name: alias.br
Result: False
Comment: State 'git.config_set' was not found in SLS 'users'
Reason: 'git' __virtual__ returned False
Changes:
And since pillar data can't be (easily) tuned according to minion's
status, we really need this check here.
My tests with Salt 2017.7.3 have shown that cmd.has_exec() is reliable
for this, contrary the what the comment was implying.

Do not try to run git config when git is not available

---

users/map.jinja
users/sudo.sls

PR fixes these issues.
```
ID: users_sudo-package
Function: pkg.installed
Name: sudo
Result: False
Comment: Brew command failed. Additional info follows:
result:
----------
pid:
15807
retcode:
1
stderr:
Error: No available formula with the name "sudo"
Warning: homebrew/core is shallow clone. To get complete history run:
git -C "$(brew --repo homebrew/core)" fetch --unshallow
Error: No previously deleted formula found.
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
stdout:
==> Searching for a previously deleted formula (in the last month)...
==> Searching for similarly named formulae...
==> Searching taps...
ID: users_sudoer-messi
Function: file.managed
Name: /etc/sudoers.d/messi
Result: False
Comment: …
```

sudo already installed on Darwin

---

pillar.example
users/init.sls

Hi 
I don't want to show private part ssh key into pillar data. I offer this feature.
Pillar example:
```YAML
users:
user_name:
ssh_keys:
privkey: salt://path_to_PRIVATEKEY
pubkey: salt://path_to_PUBLICKEY
```

Support "salt://path_to_keyname" ssh_key definition in users:"user name":ssh_keys:"privkey|pubkey" pillar data

---

users/init.sls

Since https://github.com/saltstack-formulas/users-formula/pull/182 the
home directory was created by salt which prevent "adduser" behavior to
copy /etc/skel in newly created directory.
Ensure the parent directory of the home dir is existing instead.

Fix default behavior of copying /etc/skel when creating home directory

---

users/init.sls

To get it to work with RHEL7 with salt 2018.x

[users/init] use dir_mode in addition to mode

---

users/defaults.yaml
users/init.sls

a few smaller changes:
- since `createhome` was referenced often, I changed it to be a variable
- even if createhome is false, it should create a passwd-entry with the home set
- fix for #164

reworked "createhome" (variable, passwd entry & issue #164)

---

pillar.example

Add `groups` section into `pillar.example` for function below:
https://github.com/saltstack-formulas/users-formula/blob/b8c6844e1000f8977e1c3a5fcc096914950f5a5d/users/init.sls#L7-L15

add example of groups init into pillar.example

---

pillar.example
users/init.sls

Groups changes:
* `groups` now support `absent` key like for `users`
* `pillar.example` updated
* `groups` now suppors `members`, `addusers` and `delusers`

Groups members

---

users/map.jinja

Add `prime_group` for MacOS. 
Fixes "no group gid 1000" issue
Verified on MacOS Mojave.
```
ID: users_bash-package
Function: pkg.installed
Name: bash
Result: True
Comment: All specified packages are already installed
Started: 22:51:20.985386
Duration: 2925.297 ms
Changes:   
----------
ID: users_/etc/sudoers.d
Function: file.directory
Name: /etc/sudoers.d
Result: True
Comment: Directory /etc/sudoers.d updated
Started: 22:51:23.914410
Duration: 1.298 ms
Changes:   
----------
/etc/sudoers.d:
New Dir
----------
ID: users_sudo-package
Function: pkg.installed
Name: sudo
Result: True
Comment: unless condition is true
Started: 22:51:23.915869
Duration: 1224.78 ms
Changes:   
----------
ID: users_sudoer-defaults
Function: file.append
Name: /etc/sudoers
Result: True
Comment: Appended 2 lines …
```

fix(macos): ensure correct prime_group value

---

pillar.example
users/user_files.sls

Added logic for setting directory mode logic in users.user_files.

added dir_mode logic for users.user_files

---

users/init.sls

* Close #198
* All details in that issue
* Solution based upon:
- https://github.com/saltstack-formulas/vault-formula/pull/35#issuecomment-509854411
---
While this repo doesn't have any testing so far, I've been working on `semantic-release`, so I've been able to test this change here: https://travis-ci.org/myii/users-formula/builds/562948812.  `opensuse` is just being a pain as usual, it's not failing with anything to do with this change.

fix(init): replace `gid_from_name` (deprecated in `develop`)

---

.travis.yml
.yamllint
pillar.example
test/integration/default/inspec.yml
test/salt/pillar/default.sls
users/defaults.yaml

* Semi-automated using `ssf-formula` (v0.5.0)
* Fix errors shown below:
```bash
users-formula$ $(grep "\- yamllint" .travis.yml | sed -e "s:^\s\+-\s\(.*\):\1:")
./users/defaults.yaml
4:1       warning  missing document start "---"  (document-start)
5:20      warning  truthy value should be one of [false, true]  (truthy)
8:21      warning  truthy value should be one of [false, true]  (truthy)
9:15      warning  truthy value should be one of [false, true]  (truthy)
10:1      error    too many blank lines (1 > 0)  (empty-lines)
pillar.example
5:20      warning  truthy value should be one of [false, true]  (truthy)
14:13     warning  truthy value should be one of [false, true]  (truthy)
16:13     warning  truthy value should be one of [false, true]  (truthy)
19:13     warning  truthy value …
```

feat(yamllint): include for this repo and apply rules throughout

---

pillar.example
test/salt/pillar/default.sls

---
No.
Found this problem some time back while testing `saltcheck` tests with this formula.
https://github.com/saltstack-formulas/users-formula/blob/5e6846b1735406395bec572f0b58c1ed39189f11/users/init.sls#L14-L21
* https://docs.saltstack.com/en/latest/ref/states/all/salt.states.group.html#salt.states.group.present
- Docs show that both have to be lists.
Found with the following `saltcheck` tests:
```sls
{%-     for section in ['members'] %}
{%-       for member in (setting.get('addusers', []) + setting.get('members', [])) %}
validate_users_group_present_{{ group }}_{{ section }}_{{ member }}_present:
module_and_function: group.info
args:
- '{{ group }}'
assertion: assertIn
assertion_section: '{{ section }}'
expected-return: '{{ member }}'
{%-       endfor %}
{%-       for member in …
```

fix(pillars): ensure `addusers` & `delusers` are lists
