saltstack-formulas/users-formula

pillar.example
users/init.sls

This adds the ability to manage the ~/.ssh/config file for users.

Add ~/.ssh/config management

---

README.rst
users/files/vimrc/vimrc
users/vimrc.sls

This will ensure that a given vimrc file in a users home dir is managed
Default it will search for a vimrc in salt://users/files/vimrc/{{ username
}}/vimrc
If this isn't found it will install salt://users/files/vimrc/vimrc

Add vimrc extension

---

README.rst
pillar.example
users/bashrc.sls
users/vimrc.sls

Made both states configurable per user in pillar data
Had to drop extend, for this otherwise the extend would be empty if manage is
False

Enable/disable bashrc/vimrc per user

---

pillar.example
users/init.sls

This will allow users change their passwords after the initial setting in Salt.

Adding support for the enforce_password option.

---

users/init.sls

SSH key pairs deployed via the user's ssh_keys_pillar dict aren't
handled the same as the user's ssh_keys, e.g., file ownership and
permissions aren't specified, and the keying material gets copied
directly into the SLS file.  This change rewrites the two templated
file.managed states to behave as follows:
- set the files' owner to be the user
- set the files' group to be the user's primary group
- for the public key, set the mode to 644 (u=rw,go=r)
- for the private key, set the mode to 600 (u=rw,g=)
- pull the files' contents directly from Pillar

Rework ssh_keys_pillar-related states

---

users/init.sls

Do not escape value of `enforce_password`

---

README.rst
pillar.example
users/files/profile/profile
users/profile.sls

Add support for .profile file

---

users/init.sls

Fixes #84, improves readability.

iteritems() -> items, break some way to long lines

---

pillar.example
users/init.sls

Adds a feature similar to ssh_keys_pillar that generates the authorized_keys file based on pillar data.

Add ssh_auth_pillar option.

---

pillar.example
users/init.sls

This adds the ability to manage entries in the ~/.ssh/known_hosts file for users.

Add possibility to manage ssh's known_hosts file.

---

pillar.example
users/init.sls

This adds the ability to manage the global git configuration in the ~/.gitconfig file for each user.

Add possibility to manage the user's global git configuration.

---

pillar.example

in an attempt to save others from digging into the source (to confirm this detail)

update pillar.example to include uid

---

pillar.example

Previous example would result in quote escaping problem

fix gitconfig url insteadOf example

---

pillar.example
users/init.sls

Add support for ssh_auth_sources.absent

---

users/init.sls

Fixing the conflict and sending a new pull request
Fixes #118
Duplicate of #120

Replace periods in username with underscores

---

users/map.jinja

I've added to map.jinja so this works on Solaris

Added Solaris

---

pillar.example
users/user_files.sls

If set, pass-through to 'template' on 'file.recurse'.

Add 'template' support to 'user_files'

---

pillar.example
users/init.sls

I needed a way to define multiple keys for one user.

add support for multiple private and public keys

---

users/init.sls

[init] add makedirs to home directory creation

---

pillar.example
users/init.sls

Added support for creating non unique users and managing only sudo rules

Unique switch

---

users/map.jinja

This fixes the missing import defaults.yaml as defaults

add import defaults.yaml

---

pillar.example
users/init.sls

Add a state for git.config_unset to remove configuration from a user's global gitconfig.

Add possibility to remove user's git config keys

---

pillar.example
users/init.sls

Update for options in newer salt versions.

Improvements for ssh known hosts handling

---

users/init.sls

adds support for [salt.states.user.present](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.user.html#salt.states.user.present) password expiration options

support password expiration

---

users/map.jinja

Add OpenBSD specific default data

added OpenBSD data

---

users/init.sls

Related to change operated in 634deac

 [users/init] use createhome from defaults

---

.travis.yml
kitchen.yml
test/integration/vimrc/README.md
test/integration/vimrc/controls/config_spec.rb
test/integration/vimrc/inspec.yml
test/salt/pillar/default.sls
test/salt/pillar/vimrc.sls
users/files/vimrc/vimrc
users/vimrc.sls

---
No.
* Closes #213.
* Completes #214 (CC: @fzipi).
* Semi-automated using https://github.com/myii/ssf-formula/pull/91
See #213 and #214 for the details.
As provided by the new tests.
This passes in Travis:
* https://travis-ci.org/myii/users-formula/builds/606361259
Specifically the new `vimrc` suite (which runs the `default` suite tests as well):
* https://travis-ci.org/myii/users-formula/jobs/606361261#L3843-L3865

fix(vimrc): ensure `vimrc` state runs

---

users/init.sls

---
No.
Fix user.present states  on MacOS:
```
users:
ADM:
sudouser: True
shell: /bin/bash
optional_groups:
- adm
- wheel
- docker
#needs sudo privledges
sudo_rules:
- 'ALL=(ALL) ALL'
----------
ID: users_ADM_user
Function: user.present
Name: ADM
Result: False
Comment: An exception occurred in this state: Traceback (most recent call last):
File "/usr/local/Cellar/salt/3001/libexec/lib/python3.7/site-packages/salt/state.py", line 2154, in call
*cdata["args"], **cdata["kwargs"]
File "/usr/local/Cellar/salt/3001/libexec/lib/python3.7/site-packages/salt/loader.py", line 2087, in wrapper
return f(*args, **kwargs)
File "/usr/local/Cellar/salt/3001/libexec/lib/python3.7/site-packages/salt/states/user.py", line 713, in present
__salt__["user.ch{0}".format(key)](name, changes.pop(key))
File …
```

fix(macos): gid must be numeric on macos

---

users/bashrc.sls
users/googleauth.sls
users/init.sls
users/profile.sls
users/vimrc.sls

salt linters complain about these.
---
No.
Changed raw file modes to the more preferred style of quoted with a leading zero

style: quote numbers and file modes
